require('signals.screen')
require('signals.client')
require('signals.ruled')
require('signals.tag')
require('signals.battery')
require('signals.bluetooth')
require('signals.volume')
require('signals.network')
